spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/finesdb?authSource=admin
      auto-index-creation: true
    redis:
      key:
        prefix:
          fine-
  main:
    banner-mode: 'off'
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081

nats:
  url: "nats://localhost:4222"

grpc:
  server:
    port: 9091
    security:
      enabled: false
