spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/finesdb?authSource=admin
      auto-index-creation: true
    redis:
      host: redis
      key:
        prefix:
          fine-
  main:
    banner-mode: 'off'
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  kafka:
    bootstrap-servers: http://kafka:29092
    properties:
      schema:
        registry:
          url: http://schema-registry:8081

nats:
  url: "nats://nats:4222"

grpc:
  server:
    port: 9091
    security:
      enabled: false
