spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/fine_database?createDatabaseIfNotExist=true
  jpa:
    defer-datasource-initialization: true
  main:
    banner-mode: 'off'
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  sql:
    init:
      mode: always


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
    root: warn
